# Generated by Django 4.2.13 on 2024-05-21 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
